### ISSUE TITLE
Tested with Electron on Windows10 ?

### ISSUE THREAD

**Issue by martinhbramwell** [mother/react-files#13]
I developed a prototype Electron app on Linux that uses 'react-files' to load _text/csv_ files.

Testing the same app on Windows 10, I find that 'react-files' sees no mime type from chosen files.  If I **do** **not** specify 'accepts' the chosen files are loaded.   If I **do** specify 'accepts' no files are loaded.

If I break at [https://github.com/mother/react-files/blob/master/src/index.js#L28](https://github.com/mother/react-files/blob/master/src/index.js#L28) , then Chrome debugger shows ...

    FileList {0: File, length: 1}
     - length:1
     v 0: File
         - lastModified:1515092677223
         v lastModifiedDate:Thu Jan 04 2018 14:04:37 GMT-0500 (Eastern Standard Time)
         - name: "Export20180104.csv"
         - path: "C:\Users\You\AppData\Roaming\sri\Export20180104.csv"
         - size: 8419
         - type: ""
         - webkitRelativePath: ""
         v __proto__: File
      v __proto__: FileList

I do not know where to look for a root cause for this, nor who to ask for help.  Would it be a defect in react-files or webkit or electron or npm on windows?

**Comment by asabhaney** [comment]
Thanks @martinhbramwell I will run some tests using Electron this week. I appreciate the inclusion of the debugger output.

**Comment by JZBo** [comment]
Greetings. I have some more input about react-file and issues with electron.

Electron does not return a file.type for most text files, like .json, .csv,, .yaml, and so on. 
At the same time, it does add a 'path' property.

The error raised is in the fileTypeAcceptable function of the Files component, because it checks that accepts is defined (true) and that file.type is defined as well (FALSE, in the case of electron). This results in the function failing because if accepts is true and file.type is not it immediately falls down to output an Error with code:1 (not a valid file type) and then returns false.

So, to check for file types in Electron, if type is empty, one should only check the extension property of the file.

I actually have a very modest proposal - it could be simple to allow in the accept array also extension strings like '*.json', '*.csv', '*.yaml', etc... and to check the file.extension of the uploaded file

**Comment by asabhaney** [comment]
Thanks for the diagnosis @JZBo, and thanks for proposing a solution! 

I think what we can do pretty easily is detect the mime type if is not provided by Electron (or perhaps other environments). Perhaps we could do mime type detection based on the extension, or if the extension is not defined, we could try and inspect the contents of the file using a library (such as https://github.com/mscdex/mmmagic). This way, we could still keep the `types` prop the same, and let the library do the heavy lifting so that the consumer of this lib doesn't have worry about when to use mime type vs extension.

Will address this issue in the next release, but certainly open to pull requests if anyone would like to give it a shot.

**Comment by asabhaney** [comment]
Closing via #14
